### PR TITLE
Reduce Noise and Add Support for New/More Services

### PR DESCRIPTION
**Pull request by tkalus**
- `get_regions_for_service()` now takes a tuple of desired regions and returns
  confluence of desired regions and regions the service is available.
- `get_client()` defaults to SDK config for region choice.
- Additional filtering-out of aws-managed resources and API strangeness.
  - KMS keys (E.G. lightsail's keys are showing up in the `ListKeys` operation).
  - Tweaked filter-choice for AWS-managed SSM patches.
  - Remove Internet Gateways attached to DefaultVPCs.
  - MediaLive `ListChannels` and `ListInputs` (sometimes) returns an empty list of Channels, but
    indicates it was truncated.
  - List MultiRegion CloudTrail trails only in their `HomeRegion`.
  - Remove AWS-provided/default CloudWatch Metrics.
  - And more...
- Additional support for many new services.
- Additional support for many ignorable exceptions.

### CODE REVIEW

**Comment by bkmeneguello** [comment]
@JohannesEbke, this PR is good.

**Comment by JohannesEbke** [comment]
Thanks @tkalus for the great PR; apologies for the late reaction.

**Comment by JohannesEbke** [comment]
@tkalus I released 0.3.0 on [PyPI](https://pypi.org/project/aws-list-all/), your changes should be in it!

**Comment by JohannesEbke** [comment]
I've just noted that "aws-list-all show" now does AWS requests due to the default detection; this breaks a bit especially if the target user does not have the credentials. I'm currently in the process of updating other things, so I'll have a look on how to fix it up.

**Pull request merged**
